name: Check Seats

on:
  workflow_dispatch:

  schedule:
    - cron: '*/30 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Install Playwright
        run: |
          playwright install chromium

      - name: Run Seat Checker
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SMOOZ_ID: ${{ secrets.SMOOZ_ID }}
          SMOOZ_PASSWORD: ${{ secrets.SMOOZ_PASSWORD }}
          TARGET_DATE: ${{ vars.TARGET_DATE }}
        run: python app/main.py